import type { Feature } from '@/types';

export const FEATURES: Feature[] = [
  {
    id: 'multi-session-sidebar',
    name: 'Multi-Session Sidebar',
    source: 'Claude Code',
    description: 'Manage multiple parallel agent sessions across repos; filter by status/project; auto-archive completed PRs',
    category: 'Agent Management',
    enabled: true,
  },
  {
    id: 'three-view-modes',
    name: 'Three View Modes',
    source: 'Claude Code',
    description: 'Verbose (full tool calls), Normal (balanced), Summary (results only) — toggle with one click',
    category: 'Interface',
    enabled: true,
  },
  {
    id: 'parallel-subagents',
    name: '8 Parallel Sub-Agents',
    source: 'Cursor 2.0',
    description: 'Run up to 8 AI agents concurrently on isolated git worktrees to prevent file conflicts',
    category: 'Agent Management',
    enabled: true,
  },
  {
    id: 'embedded-browser',
    name: 'Embedded Browser',
    source: 'Cursor 2.0',
    description: 'Agents test their own code by launching a built-in browser, inspecting DOM elements, and iterating on UI',
    category: 'Testing',
    enabled: true,
  },
  {
    id: 'mission-control',
    name: 'Manager Surface / Mission Control',
    source: 'Google Antigravity',
    description: 'Spawn, monitor, and direct multiple agents; assign 5+ agents in parallel with task cards',
    category: 'Agent Management',
    enabled: true,
  },
  {
    id: 'dual-interface',
    name: 'Dual Interface (Editor + Manager)',
    source: 'Google Antigravity',
    description: 'Editor View (synchronous, fine-grained) and Manager Surface (asynchronous, fire-and-forget)',
    category: 'Interface',
    enabled: true,
  },
  {
    id: 'visual-artifacts',
    name: 'Visual Artifacts',
    source: 'Google Antigravity',
    description: 'Agents deliver visual outputs — task checklists, implementation plans, screen recordings',
    category: 'Output',
    enabled: true,
  },
  {
    id: 'cascade-planning',
    name: 'Cascade Background Planning',
    source: 'Windsurf',
    description: 'A planning agent continuously refines long-term plans while the model focuses on short-term actions',
    category: 'Agent Behavior',
    enabled: true,
  },
  {
    id: 'command-center',
    name: 'Agent Command Center',
    source: 'Windsurf',
    description: 'Unified Kanban-style dashboard managing all agents (local + cloud) in one place',
    category: 'Agent Management',
    enabled: true,
  },
  {
    id: 'remote-agent-machine',
    name: 'Remote Agent Machine',
    source: 'Devin',
    description: 'Open the agent\'s VS Code in a browser tab; directly read and edit the agent\'s files as it works',
    category: 'Agent Behavior',
    enabled: false,
    isPremium: true,
  },
  {
    id: 'fire-and-forget-prs',
    name: 'Fire-and-Forget PRs',
    source: 'Devin',
    description: 'Hand the agent a ticket or task; receive a completed pull request without monitoring',
    category: 'GitHub',
    enabled: true,
  },
  {
    id: 'three-ui-options',
    name: '3 UI Design Options',
    source: 'v0 by Vercel',
    description: 'Agent generates three design variations for the user to choose from before full implementation',
    category: 'Design',
    enabled: true,
  },
  {
    id: 'figma-to-code',
    name: 'Figma/Screenshot-to-Code',
    source: 'v0 by Vercel',
    description: 'Upload a design mockup or screenshot; agent generates matching code with design tokens',
    category: 'Design',
    enabled: true,
  },
  {
    id: 'design-canvas',
    name: 'Design Canvas',
    source: 'Replit',
    description: 'Visual editing surface for layouts, styles, and content — edit visually, code updates automatically',
    category: 'Design',
    enabled: true,
  },
  {
    id: 'app-testing',
    name: 'Automatic UI Acceptance Testing',
    source: 'Replit',
    description: 'Agent tests its own work before presenting to human — the "gold standard" approach',
    category: 'Testing',
    enabled: true,
  },
  {
    id: 'multimodal-input',
    name: 'Multimodal Input',
    source: 'Codex CLI',
    description: 'Pass screenshots or diagrams; agent generates or edits code to match visual intent',
    category: 'Input',
    enabled: true,
  },
  {
    id: 'architect-mode',
    name: 'Architect Mode',
    source: 'Aider',
    description: 'Two-model pipeline — a strong "architect" model reasons; a faster "editor" model implements',
    category: 'Agent Behavior',
    enabled: true,
  },
  {
    id: 'plan-act-modes',
    name: 'Plan/Act Modes',
    source: 'Cline',
    description: 'Agent creates a plan for user approval; only after approval does it act; human-in-the-loop',
    category: 'Agent Behavior',
    enabled: true,
  },
  {
    id: 'spec-driven-dev',
    name: 'Spec-Driven Development',
    source: 'Kiro',
    description: 'Agent generates requirements, designs, and task lists BEFORE writing code; spec approval gates implementation',
    category: 'Planning',
    enabled: true,
  },
  {
    id: 'property-testing',
    name: 'Property-Based Testing',
    source: 'Kiro',
    description: 'Automatically verifies generated code matches the specification using property-based tests',
    category: 'Testing',
    enabled: false,
  },
  {
    id: 'cloud-async-agents',
    name: 'Cloud Async Agents',
    source: 'GitHub Copilot',
    description: 'Agents work in the cloud even when offline; tasks continue; PR appears when done',
    category: 'GitHub',
    enabled: true,
  },
  {
    id: 'agents-panel',
    name: 'Agents Panel Overlay',
    source: 'GitHub Copilot',
    description: 'Lightweight overlay on any GitHub page to delegate tasks without navigating away',
    category: 'GitHub',
    enabled: true,
  },
  {
    id: 'million-token-context',
    name: '1M Token Context',
    source: 'Gemini CLI',
    description: 'Full codebase ingestion without chunking; understand entire monorepos at once',
    category: 'Context',
    enabled: true,
  },
  {
    id: 'visual-canvas-git',
    name: 'Visual Canvas + Git',
    source: 'Fusion/Builder.io',
    description: 'Design on a visual canvas writing real code using existing components; changes appear as real git PRs',
    category: 'Design',
    enabled: false,
  },
  {
    id: 'gpu-rendering',
    name: 'GPU-Accelerated Rendering',
    source: 'Zed',
    description: 'Native performance for large files; multi-megabyte files open without jank',
    category: 'Performance',
    enabled: true,
  },
  {
    id: 'transparent-reasoning',
    name: 'Transparent Reasoning',
    source: 'Amazon Q Developer',
    description: 'Agent shows its thinking process; choose automated modifications or step-by-step confirmation',
    category: 'Agent Behavior',
    enabled: true,
  },
  {
    id: 'context-engine',
    name: 'Context Engine',
    source: 'Augment Code',
    description: 'Indexes entire technology stacks across multiple repos; understands how your whole architecture connects',
    category: 'Context',
    enabled: true,
  },
  {
    id: 'micro-app-marketplace',
    name: 'Micro-App Marketplace',
    source: 'MarsX',
    description: 'Assemble projects from pre-built, community-contributed Micro-Apps (auth, payments, landing pages)',
    category: 'Marketplace',
    enabled: true,
  },
  {
    id: 'theme-from-prompt',
    name: 'Theme-from-Prompt',
    source: 'Google Stitch',
    description: 'AI generates complete UI themes from natural language descriptions and reference images',
    category: 'Design',
    enabled: true,
  },
  {
    id: '500-model-support',
    name: '500+ Model Support',
    source: 'Kilo Code',
    description: 'Connect to any OpenAI-compatible endpoint; maximum model flexibility',
    category: 'Models',
    enabled: false,
  },
];

export const FEATURE_CATEGORIES = [...new Set(FEATURES.map((f) => f.category))];
