import type { ThemeDefinition } from '@/types';

export const THEMES: ThemeDefinition[] = [
  {
    id: 'cursor',
    label: 'Cursor Dark',
    bg: '#0D0D0D',
    surface: '#161616',
    border: '#2A2A2A',
    accent: '#2563EB',
    accentFg: '#FFFFFF',
    text: '#F0F0F0',
    textMuted: '#6B7280',
    fontMono: "'JetBrains Mono', monospace",
    fontSans: "'Inter', sans-serif",
    radius: '6px',
  },
  {
    id: 'claude',
    label: 'Claude Warm',
    bg: '#1E1E2E',
    surface: '#262637',
    border: '#3A3A5C',
    accent: '#7C3AED',
    accentFg: '#FFFFFF',
    text: '#E8E8F0',
    textMuted: '#8B8BA7',
    fontMono: "'Fira Code', monospace",
    fontSans: "'Inter', sans-serif",
    radius: '8px',
  },
  {
    id: 'chatgpt',
    label: 'ChatGPT',
    bg: '#F7F7F8',
    surface: '#FFFFFF',
    border: '#E5E5E5',
    accent: '#10A37F',
    accentFg: '#FFFFFF',
    text: '#202123',
    textMuted: '#6E6E80',
    fontMono: "'Roboto Mono', monospace",
    fontSans: "'Söhne', 'Inter', sans-serif",
    radius: '8px',
  },
  {
    id: 'grok',
    label: 'Grok',
    bg: '#000000',
    surface: '#111111',
    border: '#333333',
    accent: '#FFFFFF',
    accentFg: '#000000',
    text: '#F5F5F5',
    textMuted: '#888888',
    fontMono: "'IBM Plex Mono', monospace",
    fontSans: "'Inter', sans-serif",
    radius: '4px',
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    bg: '#0F172A',
    surface: '#1E293B',
    border: '#334155',
    accent: '#0EA5E9',
    accentFg: '#FFFFFF',
    text: '#E2E8F0',
    textMuted: '#64748B',
    fontMono: "'Source Code Pro', monospace",
    fontSans: "'Inter', sans-serif",
    radius: '6px',
  },
  {
    id: 'spotify',
    label: 'Spotify',
    bg: '#121212',
    surface: '#191414',
    border: '#282828',
    accent: '#1DB954',
    accentFg: '#000000',
    text: '#FFFFFF',
    textMuted: '#A7A7A7',
    fontMono: "'Circular', 'Inter', monospace",
    fontSans: "'Circular', 'Inter', sans-serif",
    radius: '500px',
  },
  {
    id: 'gemini',
    label: 'Gemini',
    bg: '#1E1E1E',
    surface: '#2A2A2A',
    border: '#3D3D3D',
    accent: '#4285F4',
    accentFg: '#FFFFFF',
    text: '#E8EAED',
    textMuted: '#9AA0A6',
    fontMono: "'Google Sans Mono', monospace",
    fontSans: "'Google Sans', 'Inter', sans-serif",
    radius: '12px',
  },
  {
    id: 'copilot',
    label: 'Copilot',
    bg: '#0D1117',
    surface: '#161B22',
    border: '#30363D',
    accent: '#00B4D8',
    accentFg: '#FFFFFF',
    text: '#C9D1D9',
    textMuted: '#8B949E',
    fontMono: "'Cascadia Code', monospace",
    fontSans: "'Segoe UI', 'Inter', sans-serif",
    radius: '6px',
  },
  {
    id: 'yfitops',
    label: 'YfitOps',
    bg: '#292F36',
    surface: '#363D45',
    border: '#4A525C',
    accent: '#FF6B6B',
    accentFg: '#FFFFFF',
    text: '#F5F5F5',
    textMuted: '#9CA3AF',
    fontMono: "'JetBrains Mono', monospace",
    fontSans: "'Inter', sans-serif",
    radius: '8px',
  },
];

export const DEFAULT_THEME_ID = 'cursor';
